spring:
  data:
    mongodb:
      host: mongodb  # Utilisez 'mongodb' si c'est le nom du service dans Docker Compose
      port: 27017
      username: bassim
      password: bassim
      database: notification
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'  # Accepte tous les packages  à modifier en prod
        spring.json.type.mapping: orderConfirmation:com.bassim.ecommerce.kafka.order.OrderConfirmation, paymentConfirmation:com.bassim.ecommerce.kafka.payment.PaymentConfirmation

  mail:
    host: mail-dev
    port: 1025
    username: bassim  # Utilisation de variables d'environnement
    password: bassim  # Utilisation de variables d'environnement
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000  # Connexion timeout en millisecondes
          timeout: 3000            # Timeout pour la lecture de la réponse
          writetimeout: 5000       # Timeout pour l'envoi du message

eureka:
  instance:
    hostname: notification-api

server:
  port: 8040  # Port sur lequel l'application tourne
